### ISSUE TITLE
Reload problems

### ISSUE THREAD

**Issue by AtharvMane** [SEDSCelestiaBPGC/Korolev#24]
No page other than homepage reloads properly when reloaded.

**Comment by plutoniumm** [comment]
Canyon please add steps to reproduce and maybe an image?
It seems like this can be a browser or device specific problem

**Comment by AtharvMane** [comment]
It seems it was a pre-rebuilding issue, the issue does not occur anymore.

**Comment by AtharvMane** [comment]
There seems to be another problem though, on reload all images return 404 error. 
Steps to reproduce:
1) Go on any page other than homepage, lets take observations page for example,
2) Reload the page.

it is observed that images return 404 error after the reload. This also does not seem to be browser related or device related since both Mozilla Firefox, Google Chrome and Opera browser all seem to show this problem.

**Comment by plutoniumm** [comment]
This seems a problem of relative URLs as opposed to absolute URLs, changing from './assets' to '/assets' should fix the problem
